MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/data/models/R-50.pkl"
  RPN:
    PRE_NMS_TOP_N_TRAIN: 10000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
    BATCH_SIZE_PER_IMAGE: 256

    STRADDLE_THRESH: -1
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    NMS: 0.5

  CLS_AGNOSTIC_BBOX_REG: True

  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 8
    NUM_CLASSES: 3  # IMPORTANT

  ROI_MASK_HEAD:
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 8  # MUST BE SAME AS POOLER_RESOLUTION AS ROI_BOX_HEAD
    RESOLUTION: 8  # MUST BE SAME AS POOLER_RESOLUTION
    SHARE_BOX_FEATURE_EXTRACTOR: True
  MASK_ON: True
DATASETS:
  TRAIN: ("coco_2014_debug",)
#  TEST: ("coco_2014_minival",)
INPUT:
  MAX_SIZE_TEST: 800
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TEST: 640
  MIN_SIZE_TRAIN: (640,)
  FLIP_PROB_TRAIN: 0.5
SOLVER:
  WEIGHT_DECAY: 0.0001
  BASE_LR: 0.0025
  IMS_PER_BATCH: 2
  STEPS: (120000, 160000)
  MAX_ITER: 320
  WARMUP_ITERS: 20

OUTPUT_DIR: "checkpoints/coco_mask_rcnn"
