MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/data/models/R-50.pkl"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
    BATCH_SIZE_PER_IMAGE: 256

  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    NMS: 0.5
  ROI_BOX_HEAD:
    NUM_CLASSES: 3  # IMPORTANT
DATASETS:
  TRAIN: ("coco_2014_debug",)
#  TEST: ("coco_2014_minival",)
INPUT:
  MAX_SIZE_TEST: 800
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TEST: 600
  MIN_SIZE_TRAIN: (600,)
  FLIP_PROB_TRAIN: 0.5
SOLVER:
  BASE_LR: 0.006
  WEIGHT_DECAY: 0.0001
  IMS_PER_BATCH: 2
  STEPS: (120000, 160000)
  MAX_ITER: 200

OUTPUT_DIR: "checkpoints/coco_faster_rcnn"
