MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/data/models/R-50.pkl"
  ROTATED: True
  RPN:
    PRE_NMS_TOP_N_TRAIN: 10000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
    BATCH_SIZE_PER_IMAGE: 256

    STRADDLE_THRESH: -1

    ANCHOR_SIZES: (32, 64, 128, 256, 512)
    ANCHOR_STRIDE: (16,)

    ANCHOR_ANGLES: (-90, -60, -30) #, -60, -30)
    ASPECT_RATIOS: (0.5, 1.0, 2.0)

    # Rotated IOU threshold
    FG_IOU_THRESHOLD: 0.7
    BG_IOU_THRESHOLD: 0.3

#    BBOX_REG_WEIGHTS: (2.0, 2.0, 2.0, 2.0, 1.0)
    BBOX_REG_WEIGHTS: (1.0, 1.0, 1.0, 1.0, 1.0)

    USE_FPN: False

  ROI_HEADS:
    USE_FPN: False

    SCORE_THRESH: 0.1

    BATCH_SIZE_PER_IMAGE: 256

    NMS: 0.4

    # Rotated IOU threshold
    FG_IOU_THRESHOLD: 0.5
    BG_IOU_THRESHOLD: 0.5

    BBOX_REG_WEIGHTS: (10.0, 10.0, 5.0, 5.0, 3.0)

  CLS_AGNOSTIC_BBOX_REG: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    NUM_CLASSES: 3  # IMPORTANT: CLS LAYER
DATASETS:
  TRAIN: ("coco_2014_debug",)
#  TEST: ("coco_2014_minival",)
INPUT:
  MAX_SIZE_TEST: 800
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TEST: 640
  MIN_SIZE_TRAIN: (640,)
  FLIP_PROB_TRAIN: 0.5
SOLVER:
  BASE_LR: 0.004
  WEIGHT_DECAY: 0.0001
  IMS_PER_BATCH: 4
  STEPS: (120000, 160000)
  MAX_ITER: 400
  WARMUP_ITERS: 20

DATALOADER:
#  ASPECT_RATIO_GROUPING: True
  NUM_WORKERS: 3

OUTPUT_DIR: "checkpoints/coco_rotated_faster_rcnn"
