MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/data/models/R-50.pkl"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256

  ROTATED: True

  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    ANCHOR_ANGLES: (-90, -60, -30) #, -60, -30)

    BATCH_SIZE_PER_IMAGE: 256
    PRE_NMS_TOP_N_TRAIN: 2500
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000

    STRADDLE_THRESH: -1

    BBOX_REG_WEIGHTS: (1.0, 1.0, 1.0, 1.0, 1.0)

  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 256
    NMS: 0.5

    BBOX_REG_WEIGHTS: (10.0, 10.0, 5.0, 5.0, 2.0)

  CLS_AGNOSTIC_BBOX_REG: True

  ROI_BOX_HEAD:
#    POOLER_RESOLUTION: 14
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"

    NUM_CLASSES: 3  # IMPORTANT

  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
DATASETS:
  TRAIN: ("coco_2014_debug",)
#  TRAIN: ("coco_loading",)
#  TEST: ("coco_2014_minival",)
INPUT:
  MAX_SIZE_TEST: 800
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TEST: 640
  MIN_SIZE_TRAIN: (640,)
  FLIP_PROB_TRAIN: 0.5
SOLVER:
  WEIGHT_DECAY: 0.0001
  BASE_LR: 0.003
  IMS_PER_BATCH: 4
  STEPS: (1700,)
  MAX_ITER: 300 # 2100
  WARMUP_ITERS: 20 #40
DATALOADER:
  SIZE_DIVISIBILITY: 32


OUTPUT_DIR: "checkpoints/coco_rotated_mask_rcnn_fpn"
