MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/data/models/R-50.pkl"
  RPN_ONLY: True
  RPN:
#    ANCHOR_ANGLES: (-90, -54, -18, 18, 54)

#    ANCHOR_SIZES: (84, 128, 224, 352)
    ANCHOR_SIZES: (64, 128, 224)
    ANCHOR_STRIDE: (16,)

    ANCHOR_ANGLES: (-90, -60, -30) #, -60, -30)
    ASPECT_RATIOS: (0.25, 0.5, 1.0, 2.0, 4.0)

    STRADDLE_THRESH: 40

    # Rotated IOU threshold
    FG_IOU_THRESHOLD: 0.6
    BG_IOU_THRESHOLD: 0.4

    NMS_THRESH: 0.5

    PRE_NMS_TOP_N_TEST: 5000
    POST_NMS_TOP_N_TEST: 100
    BATCH_SIZE_PER_IMAGE: 256

    # Default weights on (dx, dy, dw, dh, dtheta) for normalizing rotated rect regression targets
    BBOX_REG_WEIGHTS: (10.0, 10.0, 5.0, 5.0, 1.0)

    RPN_HEAD: "SingleConvRRPNHead"
  ROTATED: True
OUTPUT_DIR: "checkpoints/coco_rotated_rpn_only"

#OUTPUT_DIR: "checkpoints/coco_rpn_only"

INPUT:
  MAX_SIZE_TEST: 640
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TEST: 480
  MIN_SIZE_TRAIN: (480,)
  FLIP_PROB_TRAIN: 0.5
DATASETS:
  TRAIN: ("coco_2014_debug",)
  # TEST: ("coco_2014_debug",)
  # TEST: ("coco_2014_minival",)
SOLVER:
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.0001
  IMS_PER_BATCH: 2 #6
  # MAX_ITER: 1000
  # STEPS: [0, 500, 800]
  MAX_ITER: 300 # 90000
  STEPS: [0, 60000, 80000]
  WARMUP_ITERS: 10
TEST:
  IMS_PER_BATCH: 1
DATALOADER:
  ASPECT_RATIO_GROUPING: True
  NUM_WORKERS: 3

