MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/data/models/R-50.pkl"
  RPN:
    PRE_NMS_TOP_N_TEST: 5000
    POST_NMS_TOP_N_TEST: 1000
    NMS_THRESH: 0.7

  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256

  ROI_BOX_HEAD:
    MLP_HEAD_DIM: 256
    NUM_CLASSES: 22  # + 1 for bg class
    POOLER_RESOLUTION: 14

  MASK_ON: True
  ROI_MASK_HEAD:
    RESOLUTION: 14 # 14  # MUST MATCH ROI_BOX_HEAD.POOLER_RESOLUTION
    PREDICTOR: "MaskRCNNC4Predictor"
    SHARE_BOX_FEATURE_EXTRACTOR: True

  VERTEX_ON: True
  ROI_VERTEX_HEAD:
    RESOLUTION: 14 # 14  # MUST MATCH ROI_BOX_HEAD.POOLER_RESOLUTION

  POSE_ON: True
  ROI_POSE_HEAD:
    FG_IOU_THRESHOLD: 0.65
INPUT:
  FLIP_PROB_TRAIN: 0.0  # no horizontal flipping UNTIL POSE CAN BE FLIPPED
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TRAIN: 480
  MAX_SIZE_TEST: 640
  MIN_SIZE_TEST: 480
#  MAX_SIZE_TRAIN: 320
#  MIN_SIZE_TRAIN: 240
#  MAX_SIZE_TEST: 320
#  MIN_SIZE_TEST: 240
DATASETS:
#  TRAIN: ("coco_2014_val",)
  TRAIN: ("cocopose_2014_debug",)
#  TEST: ("coco_2014_debug",)
  # TEST: ("coco_2014_minival",)
SOLVER:
  OPTIMIZER: "Adam"
  WARMUP_ITERS: 30
  BASE_LR: 0.002
  WEIGHT_DECAY: 0.00001
  IMS_PER_BATCH: 2
  MAX_ITER: 501
  STEPS: [0, 1300, 4500] # , 960]
  CHECKPOINT_PERIOD: 2500
#  MAX_ITER: 90000
#  STEPS: [0, 60000, 80000]
TEST:
  IMS_PER_BATCH: 1
DATALOADER:
  ASPECT_RATIO_GROUPING: True
  NUM_WORKERS: 3

OUTPUT_DIR: "./checkpoints/lov_debug_pose_res14"