MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/data/models/R-50.pkl"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
  ROI_MASK_HEAD:
    PREDICTOR: "MaskRCNNC4Predictor"
    SHARE_BOX_FEATURE_EXTRACTOR: True
  MASK_ON: True
  ROI_BOX_HEAD:
    MLP_HEAD_DIM: 512
  ROI_HEADS: 
    BATCH_SIZE_PER_IMAGE: 256
INPUT:
  MAX_SIZE_TEST: 800
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TEST: 600
  MIN_SIZE_TRAIN: 600
DATASETS:
  TRAIN: ("coco_2014_val",)
  TEST: ("coco_2014_debug",)
  # TEST: ("coco_2014_minival",)
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  IMS_PER_BATCH: 2
  # MAX_ITER: 1000
  # STEPS: [0, 500, 800]
  MAX_ITER: 90000
  STEPS: [0, 60000, 80000]
TEST:
  IMS_PER_BATCH: 1
DATALOADER:
  ASPECT_RATIO_GROUPING: True
  NUM_WORKERS: 3
